version: '3.9'
services:
  kavita:
    image: jvmilazz0/kavita:latest
    pull_policy: always
    volumes:
      - ./data:/kavita/config
      - /path/to/your/book/folder:/library
    ports:
      - "8097:5000"
    restart: unless-stopped