# This is my first try at creating Workflows

name: Test GitHub Actions

on: 
  workflow_dispatch:
    inputs:
      spin-up-container:
        description: Container
        required: true
        default: jellyfin
        type: choice
        options:
          - jellyfin
          - kavita

env:
  CONTAINER: ${{ inputs.spin-up-container }}

jobs:
  first-job:
    name: First Test Job
    runs-on: ubuntu-latest

    steps:
    - name: Using my first GitHub Action to copy the code to the runner
      uses: actions/checkout@v3

    - name: Running my first bash command using GitHub Actions
      run: echo "This is my first Github Actions Workflow"

    - name: Print chosen container
      run: echo "The chosen container is $CONTAINER"

    - name: Trying to print the contents of the directories
      run: |
        echo "Listing all directories in the working directory"
        ls -lh

    - name: Spinning up and inspecting the jellyfin container
      if: ${{ env.CONTAINER == 'jellyfin' }}
      run: |
        cd ./docker-compose/jellyfin
        docker-compose up -d
        CONT=$(docker ps -q | head -n 1)
        docker inspect $CONT

    - name: Spinning up the kavita container
      if: ${{ env.CONTAINER == 'kavita' }}
      run: |
        cd ./docker-compose/kavita
        docker-compose up -d
        docker inspect kavita
      

